### PR TITLE
Fix part 05 step 06

### LINKED ISSUE #731: Part 5 Step 6 needs fixed
6.5.6.1.a. DS DM20 {(send Request (PGN 59904) for PGN 49664 (SPN 3048)]) to OBD ECU(s) that provided DM20 data in part 1.

It doesn't look at the DM20's from Part 1

### PR DESCRIPTION
**Pull request by mmschaefer**
Fix #731 - Fix Part05Step06 to check the response from a DM20 request made in part 01.

### CODE REVIEW

File: src-test/org/etools/j1939_84/controllers/part05/Part05Step06ControllerTest.java [hunk 1]
```diff
@@ -148,7 +148,9 @@ public void testHappyPathNoFailures() {
         var dm20Packet = new DM20MonitorPerformanceRatioPacket(Packet.create(PGN, 0x00, data));
         when(diagnosticMessageModule.requestDM20(any(), eq(0))).thenReturn(BusResult.of(dm20Packet));
 
-        dataRepository.putObdModule(new OBDModuleInformation(0));
+        OBDModuleInformation obdModuleInformation = new OBDModuleInformation(0);
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part05/Part05Step06ControllerTest.java:151]: This test should be updated to also have a module that doesn't have a DM20 packet stored in part1.

**Review by gumbelmj — APPROVED** [review]

**Review by gumbelmj — APPROVED** [review]
