### PR TITLE
Fix Verbiage as described in the Doc 

### LINKED ISSUE #652: Titles should start with "Step" and not end with "."
The messages in the progress bar as well as the step references in the report should be consistent format:
> Step 6.X.Y Action performing
> Start 6.X.Y Title

### PR DESCRIPTION
**Pull request by mmschaefer**
Fix #652 - fix the display of the Step numbers, and information displayed to the users.

### CODE REVIEW

File: src-test/org/etools/j1939_84/controllers/part03/Part03Step16ControllerTest.java [hunk 1]
```diff
@@ -179,7 +179,7 @@ public void testUserAbortForFail() {
         String outcomeMessage = "User cancelled testing at Part 3 Step 16";
         verify(mockListener).addOutcome(PART_NUMBER, STEP_NUMBER, ABORT, outcomeMessage);
 
-        String expectedMessages = "Part 3, Step 16 Turn Engine Off and keep the ignition key in the off position" +
+        String expectedMessages = "Test 3.16 - Turn Engine Off and keep the ignition key in the off position" +
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part03/Part03Step16ControllerTest.java]: This needs to be "Test 6.3.16"

File: src-test/org/etools/j1939_84/controllers/part08/Part08Step16ControllerTest.java [hunk 2]
```diff
@@ -178,11 +178,11 @@ public void testHappyPathNoFailures() {
 
         // 6.8.16.1.c With the key in the off position remove the implanted Fault B, according to the manufacturer’s
         // instructions for restoring the system to a fault- free operating condition.
-        String urgentMessages3 = "With the key in the off position remove the implanted Fault B, according to the manufacturer’s"
+        String urgentMessages3 = "Step 6.8.16.1.c - With the key in the off position remove the implanted Fault B, according to the manufacturer’s"
                 + NL;
         urgentMessages3 += "instructions for restoring the system to a fault- free operating condition." + NL;
         urgentMessages3 += "Press OK to continue the testing.";
-        String expectedTitle3 = "6.8.16.1.c";
+        String expectedTitle3 = "Test 8.16";
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part08/Part08Step16ControllerTest.java]: This needs to be "Test 6.8.16"

File: src-test/org/etools/j1939_84/controllers/part10/Part10Step02ControllerTest.java [hunk 3]
```diff
@@ -162,10 +162,10 @@ public void testHappyPathNoFailures() {
         verify(engineSpeedModule, atLeastOnce()).getKeyState();
         verify(engineSpeedModule, atLeastOnce()).getEngineSpeedAsString();
 
-        String urgentMessages = "Wait for manufacturer’s recommended time for Fault B to be detected as passed."
+        String urgentMessages = "Step 6.10.2.1.a - Wait for manufacturer’s recommended time for Fault B to be detected as passed."
                 + NL;
         urgentMessages += "Press OK to continue the testing.";
-        String expectedTitle = "Step 6.10.2.1.a";
+        String expectedTitle = "Test 10.2";
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part10/Part10Step02ControllerTest.java]: This should be "Test 6.10.2"

File: src-test/org/etools/j1939_84/controllers/part10/Part10Step02ControllerTest.java [hunk 4]
```diff
@@ -243,10 +243,10 @@ public void testAnsweredNoToQuestion() {
...
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part10/Part10Step02ControllerTest.java]: This should be "Test 6.10.2"

File: src-test/org/etools/j1939_84/controllers/part10/Part10Step05ControllerTest.java [hunk 5]
```diff
@@ -162,10 +162,10 @@ public void testHappyPathNoFailures() {
         verify(engineSpeedModule, atLeastOnce()).getKeyState();
         verify(engineSpeedModule, atLeastOnce()).getEngineSpeedAsString();
 
-        String urgentMessages = "Wait for manufacturer’s recommended time for Fault B to be detected as passed."
+        String urgentMessages = "Step 6.10.5.1.a - Wait for manufacturer’s recommended time for Fault B to be detected as passed."
                 + NL;
         urgentMessages += "Press OK to continue the testing.";
-        String expectedTitle = "Step 6.10.5.1.a";
+        String expectedTitle = "Test 10.5";
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part10/Part10Step05ControllerTest.java]: This should be "Test 6.10.5"

File: src/org/etools/j1939_84/controllers/part03/Part03Step16Controller.java [hunk 6]
```diff
@@ -60,7 +60,7 @@
     @Override
     protected void run() throws Throwable {
         // 6.3.16.1.a. Turn the engine off.
-        incrementProgress("Part 3, Step 16 Turn Engine Off and keep the ignition key in the off position");
+        incrementProgress("Test 3.16 - Turn Engine Off and keep the ignition key in the off position");
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part03/Part03Step16Controller.java]: This should be "Test 6.3.16"

File: src/org/etools/j1939_84/controllers/part08/Part08Step16Controller.java [hunk 7]
```diff
@@ -63,37 +62,33 @@ protected void run() throws Throwable {
...
-                + NL + "instructions for restoring the system to a fault- free operating condition.",
-                                 stepId));
-        String message = "With the key in the off position remove the implanted Fault B, according to the manufacturer’s"
+    private void waitForFaultRemoval() throws InterruptedException {
+        incrementProgress("Step 6.8.16.1.c - With Key OFF, remove the implanted Fault B");
+        String message = "Step 6.8.16.1.c - With the key in the off position remove the implanted Fault B, according to the manufacturer’s"
                 + NL + "instructions for restoring the system to a fault- free operating condition." + NL;
         message += "Press OK to continue the testing.";
-        displayInstructionAndWait(message, stepId, WARNING);
+        displayInstructionAndWait(message, "Test 8.16", WARNING);
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part08/Part08Step16Controller.java]: This should be "Test 6.8.16"

**Review by gumbelmj — CHANGES_REQUESTED** [review]
The messages need to have "6." appended in places

**Review by gumbelmj — APPROVED** [review]
