### PR TITLE
Don't count TP errors as timing errors. (#947)

### LINKED ISSUE #947: Timing Error Count is incorrect
Timing Error Count is incorrect 

The correct count is 2; count for “TIMING: Late” instead of “timing:”

Log File Name: C:\CdriveSave\new j1939-84\v307 786b Link2.j1939-84

TEST SUMMARY REPORT
OUTCOME: 
Failures:    10	// I think this is the best current 786 can do? ETS looks that way to me too, Bob
Warnings:    29	// I didn’t look at these. ETS: No false failures were perceived 
Information: 0
Incomplete:  0
Timing:      15	// This count is wrong; it is counting DA text along with late responses
Passes:      168	// The correct count is 2; look for “TIMING: Late” instead of “timing:”

### PR DESCRIPTION
**Pull request by battjt**
We were counting the TP errors as timing errors.  Now we do not.

### CODE REVIEW

File: src/org/etools/j1939_84/bus/j1939/J1939TP.java [hunk 1]
```diff
@@ -492,9 +492,6 @@ public void setJ1939(J1939 j1939) {
     }
 
     public void warn(String msg, Object... a) {
-        if (j1939 != null) {
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/bus/j1939/J1939TP.java:495]: Since j1939 is only needed in this class to count warnings, we should remove the member and the setter.

**Review by gumbelmj — CHANGES_REQUESTED** [review]
Need to remove the j1939 member and setter in `J1939TP`

File: src/org/etools/j1939_84/bus/j1939/J1939TP.java (hunk 1 above)
Comment (battjt) [reply src/org/etools/j1939_84/bus/j1939/J1939TP.java:495]: I don't know how to indicate that this conversation is resolved in a later commit.  I hit the "Resolve conversation" button, but below it still says "Changes requested".

Comment (gumbelmj) [reply src/org/etools/j1939_84/bus/j1939/J1939TP.java:495]: I think you can "dismiss" my review and then request a new review.

**Review by gumbelmj — APPROVED** [review]
