### PR TITLE
Fix #932 - Notify user of second device using SA F9

### LINKED ISSUE #932: SW - Notify user of second device using SA F9.
From j1939-84 created by [battjt](https://github.com/battjt): battjt/j1939-84#928  

Provide notice for extraneous queries from SA F9,
When extraneous queries, not sent by the SAE J1939-84 software are observed:
1. Print a time stamped message in the log:
_HH:MM:SS.SSSS ccccccF9 [n] XX XX XX XX XX XX XX 
WARN: Unexpected Service Tool Message from SA F9 observed. Test results uncertain. False failures are possible._
2. Add a pop up message for the UI
_Unexpected Service Tool Query from SA F9 observed. Test results uncertain. False failures are possible._
Should a 2nd Query appear while this Pop-up is displayed, a 2nd Popup will not be displayed.
This popup shall not interfere with the user interface pop ups, and allow the user to respond to them.

### PR DESCRIPTION
**Pull request by gumbelmj**
Resolves  #932 

@battjt, I need you to test this with an adapter.

I created an `EventBus` which is intended to replace the `ResultsListener`.  I started to replace the `ResultsListener` everywhere and the change grew too large and too risky to implement now. 

So as a stop-gap, the `Controller` will listen for the `Event`s on the `EventBus` and send them to the rest of the app via the `CompositeResultsListener`. 

In V3.1 we can replace the `ResultsListener` which will clean up a lot of   ##code.

### CODE REVIEW

**Comment by battjt** [comment]
That's a lot of code to avoid a single callback.

**Comment by battjt** [comment]
"False failures are possible" is like saying "shooting yourself in the head may cause injury".  50% of queries that use TP will fail.

File: src/org/etools/j1939_84/bus/RP1210Bus.java [hunk 1]
```diff
@@ -382,12 +353,41 @@ public void stop() throws BusException {
...
-            rtnCode = (short) Math.abs(rtnCode);
-            byte[] buffer = new byte[256];
-            rp1210Library.RP1210_GetErrorMsg(rtnCode, buffer);
-            throw new BusException("Error (" + rtnCode + "): " + new String(buffer, StandardCharsets.UTF_8).trim());
+            String errorMessage = getErrorMessage(rtnCode);
+            throw new BusException(errorMessage);
+        }
+    }
+
+    private final AtomicBoolean reportedImposter = new AtomicBoolean(false);
```
Comment (battjt) [inline src/org/etools/j1939_84/bus/RP1210Bus.java]: Should be a boolean.  It is only accessed from one thread.

**Comment by gumbelmj** [comment]
> "False failures are possible" is like saying "shooting yourself in the head may cause injury". 50% of queries that use TP will fail.

I'm using the language from Eric.  I think the first time the users encounter this error, they will learn to just quit and move to a different truck or disconnect the imposter.

File: src/org/etools/j1939_84/bus/RP1210Bus.java (hunk 1 above)
Comment (gumbelmj) [reply src/org/etools/j1939_84/bus/RP1210Bus.java:363]: > That's a lot of code to avoid a single callback.

I agree.  I had already developed the `EventBus` and left all that in there.  I didn't want to hack in a fix.  I already didn't like that we passed the `ResultsListener` to the J1939 layer, but I didn't have a better solution at the time.

**Comment by gumbelmj** [comment]
> That's a lot of code to avoid a single callback.

I agree.  I had already developed the `EventBus` and left all that in there.  I didn't want to hack in a fix.  I already didn't like that we passed the `ResultsListener` to the J1939 layer, but I didn't have a better solution at the time.

**Comment by battjt** [comment]
I'm fixing some pre-existing threading issues in RP1210Bus.  I'll use this branch, since they are inflated and conflict with these changes.

**Comment by gumbelmj** [comment]
> I'm fixing some pre-existing threading issues in RP1210Bus. I'll use this branch, since they are inflated and conflict with these changes.

Once you approve this, I'l merge it and you can just branch from there.  Don't add to this branch.
