### PR TITLE
Fix Part 02 Step 16

### LINKED ISSUE #730: Part 2 Step 16 needs fixed
// 6.2.16.4.b. Fail if NACK received from OBD ECUs that responded to the global query in part 1.
this doesn't check who responded in Part1

### PR DESCRIPTION
**Pull request by mmschaefer**
Fix #730 - Fix part 02 step 16

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/part02/Part02Step16Controller.java [hunk 1]
```diff
@@ -162,31 +163,29 @@ protected void run() throws Throwable {
...
+        var obdAddresses = getDataRepository().getObdModules()
+                                              .stream()
+                                              .filter(m -> m.get(DM34NTEStatus.class, 1) != null)
+                                              .map(OBDModuleInformation::getSourceAddress)
+                                              .collect(Collectors.toList());
 
         // 6.2.16.3.a. DS DM34 to each OBD ECU which responded to the DM34 global request in step 1.
-        var dsResponses = obdAddresses.stream()
-                                      .map(a -> getDiagnosticMessageModule().requestDM34(getListener(), a))
+        var dsResponses = getDataRepository().getObdModules()
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part02/Part02Step16Controller.java]: This stream should start with the `obdAddresses`.

```
var dsResponses  = obdAddresses.stream().map(a -> getDia.....)
```

**Review by gumbelmj — CHANGES_REQUESTED** [review]

File: src/org/etools/j1939_84/controllers/part02/Part02Step16Controller.java [hunk 2]
```diff
@@ -162,31 +163,29 @@ protected void run() throws Throwable {
...
+                                              .stream()
+                                              .filter(m -> m.get(DM34NTEStatus.class, 1) != null)
+                                              .map(OBDModuleInformation::getSourceAddress)
+                                              .collect(Collectors.toList());
 
         // 6.2.16.3.a. DS DM34 to each OBD ECU which responded to the DM34 global request in step 1.
-        var dsResponses = obdAddresses.stream()
+        var dsResponses = obdAddresses
+                                             .stream()
+                                      .filter(a -> {
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part02/Part02Step16Controller.java]: You don't need to check this again.  The `obdAddresses` already did that.

**Review by gumbelmj — CHANGES_REQUESTED** [review]

**Review by gumbelmj — APPROVED** [review]
