### PR TITLE
Fix #1004 Waiting for DTCs doesn't work with multiple modules

### LINKED ISSUE #1004: Waiting for DTCs doesn't work with multiple modules
Reported from field:

I’ve located a bug during testing of the new -84 tool that may be similar to a statement you made in this email: “Failure implants are still required to succeed. Permitting the test to proceed when DM6 and DM12 are not detected is planned for the following maintenance contract.”

I believe since we use multiple OBD ECUs and faults from different ECUs to complete the -84 test, depending on if it’s a heavy duty or medium duty engine, that we are seeing an issue.

At “Start Test 3.2 - DM6: Emission related pending DTCs” the test won’t progress unless it sees a pending fault in its DM6 global response.

In the OBD ECU (DM6 from Engine #2 (1)) we use for heavy duty, it recognizes the pending fault and the test progresses.

In the OBD ECU (DM6 from Exhaust Emission Controller (61)) we use for medium duty, it does not recognize the pending fault and the test wont progress. It keeps trying for 300 attempts and then asks if you want to continue, even though I can see the pending fault in the data from the log file at attempt 1.

### PR DESCRIPTION
**Pull request by gumbelmj**
Resolves #1004 

There was no filter in the chain to find only the response that contains DTCs.

Also updated the tests and fixed a previously broken test.

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/part03/Part03Step02Controller.java [hunk 1]
```diff
@@ -89,6 +89,7 @@ protected void run() throws Throwable {
             foundDTC = globalPackets.stream()
                                     .map(DiagnosticTroubleCodePacket::getDtcs)
                                     .map(dtcs -> !dtcs.isEmpty())
+                                    .filter(hasDTCs -> hasDTCs)
                                     .findFirst()
```
Comment (battjt) [inline src/org/etools/j1939_84/controllers/part03/Part03Step02Controller.java]: foundDTC = globalPackets.stream().anyMatch(p->!p.getDtcs().isEmpty());

**Review by battjt — APPROVED** [review]
Just the one extra verbose pattern (repeated a couple times) that could be simplified, but doesn't change the functionality.

File: src/org/etools/j1939_84/controllers/part03/Part03Step02Controller.java (hunk 1 above)
Comment (gumbelmj) [reply src/org/etools/j1939_84/controllers/part03/Part03Step02Controller.java]: Thanks.  Updated
