### PR TITLE
Fix #932 - Notify user of second device using SA F9 - Add Logic to Read Vehicle Info

### LINKED ISSUE #932: SW - Notify user of second device using SA F9.
From j1939-84 created by [battjt](https://github.com/battjt): battjt/j1939-84#928  

Provide notice for extraneous queries from SA F9,
When extraneous queries, not sent by the SAE J1939-84 software are observed:
1. Print a time stamped message in the log:
_HH:MM:SS.SSSS ccccccF9 [n] XX XX XX XX XX XX XX 
WARN: Unexpected Service Tool Message from SA F9 observed. Test results uncertain. False failures are possible._
2. Add a pop up message for the UI
_Unexpected Service Tool Query from SA F9 observed. Test results uncertain. False failures are possible._
Should a 2nd Query appear while this Pop-up is displayed, a 2nd Popup will not be displayed.
This popup shall not interfere with the user interface pop ups, and allow the user to respond to them.

### PR DESCRIPTION
**Pull request by gumbelmj**
Further resolves #932 by checking for imposters when reading the vehicle information

Screen Shot 2021-04-05 at 3 05 38 PM

### CODE REVIEW

File: src/org/etools/j1939_84/bus/Bus.java [hunk 1]
```diff
@@ -94,4 +94,8 @@ default AutoCloseable log(Function<Packet, String> prefix) throws BusException {
      */
     Packet send(Packet packet) throws BusException;
 
+    default boolean foundImposter() {
```
Comment (battjt) [inline src/org/etools/j1939_84/bus/Bus.java]: I already added imposterDetected() to trunk based on yesterday's meeting.  I didn't add the default method, to avoid accidentally implementing it on a Bus, like J1939TP, which needs to return "bus.imposterDetected();".

**Review by battjt — APPROVED** [review]
Other than the minor merge conflicts in Bus and subclasses, I approve.

**Comment by gumbelmj** [comment]
Put your branch up for review. After we merge it, I’ll merge it into this branch and update it to resolve the conflicts. 

Matt

On Apr 6, 2021, at 07:27, Joe Batt ***@***.***> wrote:

﻿
@battjt approved this pull request.

Other than the minor merge conflicts in Bus and subclasses, I approve.

In src/org/etools/j1939_84/bus/Bus.java:

> @@ -94,4 +94,8 @@ default AutoCloseable log(Function<Packet, String> prefix) throws BusException {
      */
     Packet send(Packet packet) throws BusException;
 
+    default boolean foundImposter() {
I already added imposterDetected() to trunk based on yesterday's meeting. I didn't add the default method, to avoid accidentally implementing it on a Bus, like J1939TP, which needs to return "bus.imposterDetected();".
