### PR TITLE
Fix #993 - Failure and warning counts incorrect in 3.0.8

### LINKED ISSUE #993: Failure and warning counts incorrect in 3.0.8
Looks like when we fixed the timing count..
Failures:    81 
Warnings:    84 
Information: 0 
Incomplete:  0 
Timing:      2 
Passes:      167 
We broke the fail and warnings counts ...

Search for FAIL: says 27 found.
Joe reports 3 * 27 were in the log.

### PR DESCRIPTION
**Pull request by gumbelmj**
Resolves #993 

Turns out the `PartResultsRespository` was being added as a listener in the `Controller` three times.  The first time was when the `OverallController` was called.  Then the listener from the `OverallController` was handed to the `PartController`, which created a new `CompositeListener` that included the `CompositeListener` from the `OverallController`.   That listener from the `PartController` was passed to the `StepController` which then created a new `CompositeListener` which added the `CompositeListener` from the `PartController` and again added the `PartResultsRespository` to the new `CompositeListener`

So the fix is to not add a `CompositeListener` to another `CompositeListener`.  Instead, if a `CompositeListener` is supplied when `setupRun()` is called, that supplied listener will be used instead of creating a new one.

I also cleaned up the `SummaryModule` (which had code is didn't really need)

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/Controller.java [hunk 1]
```diff
@@ -367,7 +367,9 @@ protected void setupProgress(int maxSteps) {
 
     private void setupRun(ResultsListener listener, J1939 j1939, ReportFileModule reportFileModule) {
         setJ1939(j1939);
-        if (reportFileModule != null) {
+        if (listener instanceof CompositeResultsListener) {
+            compositeListener = (CompositeResultsListener) listener;
+        } else if (reportFileModule != null) {
             compositeListener = new CompositeResultsListener(listener, reportFileModule, partResultRepository);
         } else {
             compositeListener = new CompositeResultsListener(listener, partResultRepository);
```
Comment (battjt) [inline src/org/etools/j1939_84/controllers/Controller.java]: Is this line only used for tests?

**Review by battjt — APPROVED** [review]
Tested on a module.  Works correctly.

File: src/org/etools/j1939_84/controllers/Controller.java (hunk 1 above)
Comment (gumbelmj) [reply src/org/etools/j1939_84/controllers/Controller.java]: That was the one used by the PartController and StepController.  It's unused now so I removed it.
