### PR TITLE
Fix #655 - run Spotbugs and fix or annotate issues found.

### LINKED ISSUE #655: SpotBugs needs to be run
After running SpotBugs any issues found need to be addressed.

### PR DESCRIPTION
**Pull request by mmschaefer**
#655

### CODE REVIEW

File: src-test/org/etools/j1939_84/bus/MultiQueueTest.java [hunk 1]
```diff
@@ -123,34 +125,41 @@ public void testDuplicateOpen() throws Exception {
         }
     }
 
-    /** Verify that building a stream with a timeout works. */
+    /**
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/bus/MultiQueueTest.java:128]: please revert this

File: src-test/org/etools/j1939_84/controllers/part02/Part02Step02ControllerTest.java [hunk 2]
```diff
@@ -51,7 +51,7 @@
 public class Part02Step02ControllerTest extends AbstractControllerTest {
     private static final int PART_NUMBER = 2;
     private static final int STEP_NUMBER = 2;
-    final int PGN = DM5DiagnosticReadinessPacket.PGN;
+    private static final int PGN = DM5DiagnosticReadinessPacket.PGN;
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part02/Part02Step02ControllerTest.java]: You'd be better off to statically import DM5DiagnosticReadinessPacket.  Then you don't even need the member.

File: src/org/etools/j1939_84/bus/Packet.java [hunk 3]
```diff
@@ -488,7 +491,7 @@ public String toTimeString() {
         /*
          * Collect data first, because timestamp is dynamic until the data is collected. This will block on the data. We
          * want to report the timestamp of final packet.
-         */ final String dataString = toString();
+         */ String dataString = toString();
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/bus/Packet.java]: can you move this to a new line

File: src/org/etools/j1939_84/bus/j1939/Lookup.java [hunk 4]
```diff
@@ -144,6 +146,8 @@ public static String getPartName(int partNumber) {
      *                 the suspect parameter number from the Diagnostic Trouble Code
      * @return     The name as defined by SAE or "Unknown" if it's not defined
      */
+    @SuppressFBWarnings(value = "RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE", justification = "Null check needs to happen here")
+
     public static String getSpnName(int spn) {
         SpnDefinition spnDef = J1939DaRepository.getInstance().findSpnDefinition(spn);
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/bus/j1939/Lookup.java]: this method will always return a non-null value.  The check needs removed and not suppressed.

File: src/org/etools/j1939_84/bus/j1939/packets/ScaledTestResult.java [hunk 5]
```diff
@@ -84,7 +87,10 @@ public int getFmi() {
      *
      * @return double
      */
+    @SuppressFBWarnings(value = "RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE", justification = "This method has several places down the line where null can end up being returned")
+
     public double getScaledTestMaximum() {
+        // null check here is redundant - getSlot() handles the null
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/bus/j1939/packets/ScaledTestResult.java]: comment needs removed

**Review by gumbelmj — CHANGES_REQUESTED** [review]

**Review by gumbelmj — APPROVED** [review]

**Review by gumbelmj — APPROVED** [review]
