### PR TITLE
Fix #1302

### LINKED ISSUE #1302: Add CSERS support Using SP 22227 as lead SPN
Add CSERS support Using SP 22227 as lead SPN

Add to 6.1.26. and 6.2.17 as 

6.1.26.27 Actions14 CSERS Support.     
a. DS request message to ECU that indicated support in DM24 for upon request SP 22227 (Current Cycle Catalyst Heat Energy Until FTP Cold Start Tracking Time) for PGs 64019 and 64020.

PG       PG Label                                                                                                             PG Acronym
64019  Cold Start Emissions Reduction Strategy Current Operating Cycle Data   CSERSC
64020  Cold Start Emissions Reduction Strategy Average Data                              CSERSA

6.1.26.28 Fail/Warn Criteria

a. Fail if either PG 64019 and PG 64020 is not provided for engines that support SPN 22227.

and 
6.2.17.27 Actions14 CSERS Support.
a. DS request message to ECU that indicated support in DM24 for upon request SP 22227 (Current Cycle Catalyst Heat Energy Until FTP Cold Start Tracking Time) for PGs 64019 and 64020.

PG PG Label PG Acronym
64019 Cold Start Emissions Reduction Strategy Current Operating Cycle Data CSERSC
64020 Cold Start Emissions Reduction Strategy Average Data CSERSA

6.2.17.28 Fail/Warn Criteria

a. Fail if either PG 64019 and PG 64020 is not provided for engines that support SPN 22227.

### PR DESCRIPTION
**Pull request by karysg**
CSERS
@battjt

### CODE REVIEW

File: src/org/etools/j1939tools/modules/CSERSModule.java [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+    }
+
+    private String printSpn(Spn spn) {
+        if (spn.isNotAvailable() || spn.isError()) {
+            return spn.getStringValue();
+        }
+
+        double value = spn.getValue();
+
+        String unit = spn.getSlot().getUnit();
```
Comment (battjt) [inline src/org/etools/j1939tools/modules/CSERSModule.java:124]: Verify this.

Comment (karysg) [reply src/org/etools/j1939tools/modules/CSERSModule.java:124]: Latest commit updates unit in table from 's' to 'min' to match calculated value. Minute chosen for better readability.
