### PR TITLE
Fix #964 - False FAIL for VIN in 6.1.5.2e

### LINKED ISSUE #964: False FAIL for VIN in 6.1.5.2e - TOOL Issue
12:03:09.1071 Global VIN Request
12:03:09.1103 18EAFFF9 [3] EC FE 00 (TX)
12:03:09.2952 18FEEC00 [18] 31 58 50 42 44 4B 39 58 31 4C 44 37 30 38 31 39 35 2A
Vehicle Identification from Engine #1 (0): 1XPBDK9X1LD708195
FAIL: 6.1.5.2.e - VIN is not valid (not 17 legal chars, incorrect checksum, or non-numeric sequence

Version detected in - J1939-84 Tool version 3.0.7

The VIN is reported correctly and the checksum is also correct. Why is there a FAIL VIN not valid?

### PR DESCRIPTION
**Pull request by gumbelmj**
Resolves #964 

The check digit should be 'X' when the `sum % 11 == 10`.  I also updated the tests to explicitly verify each check digit.

### CODE REVIEW

File: src-test/org/etools/j1939_84/utils/VinDecoderTest.java [hunk 1]
```diff
@@ -85,6 +85,19 @@ public void testIsVinValid() {
         assertFalse("Non-numeric sequence", instance.isVinValid("PX0W9XD10RZL37HD7"));
 
         assertTrue("VIN is valid", instance.isVinValid("2G1WB5E37E1110567"));
+        assertTrue("VIN is valid", instance.isVinValid("1XPBDK9X1LD708195"));
+
+        assertTrue("Check Digit 0:", instance.isVinValid("38Z63P7W0GCRB5050"));
+        assertTrue("Check Digit 1:", instance.isVinValid("1VTAZ3NR1UZA70835"));
```
Comment (battjt) [inline src-test/org/etools/j1939_84/utils/VinDecoderTest.java]: This VIN is not valid.  U is not a valid year.

**Review by battjt — DISMISSED** [review]
isValid should check year digit, right?

**Review by battjt — APPROVED** [review]
